import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const sourceDir = path.resolve(__dirname, '../../example');
const targetDir = path.resolve(__dirname, '../template');

function copyRecursiveSync(src: string, dest: string): void {
  const exists = fs.existsSync(src);
  const stats = exists && fs.statSync(src);
  const isDirectory = exists && stats && stats.isDirectory();

  if (isDirectory) {
    const basename = path.basename(src);
    if (basename === 'node_modules' || basename === '.svelte-kit' || basename === 'dist') return;

    fs.mkdirSync(dest, { recursive: true });
    fs.readdirSync(src).forEach((childItemName) => {
      copyRecursiveSync(path.join(src, childItemName), path.join(dest, childItemName));
    });
  } else {
    // Skip package.json and lockfiles as they are generated by the CLI
    const skipFiles = ['package.json', 'bun.lockb', 'pnpm-lock.yaml', 'package-lock.json'];
    if (skipFiles.includes(path.basename(src))) return;
    fs.copyFileSync(src, dest);
  }
}

// Clean and recreate template
if (fs.existsSync(targetDir)) {
  fs.rmSync(targetDir, { recursive: true, force: true });
}
fs.mkdirSync(targetDir, { recursive: true });

// Copy example source
copyRecursiveSync(sourceDir, targetDir);

// Rename .gitignore to _gitignore because npm publish ignores .gitignore
const gitignoreSrc = path.join(targetDir, '.gitignore');
const gitignoreDest = path.join(targetDir, '_gitignore');
if (fs.existsSync(gitignoreSrc)) {
  fs.renameSync(gitignoreSrc, gitignoreDest);
}

console.log('Template synced successfully from /example!');
